-- RLS Policies for Custom JWT Authentication
-- This migration updates RLS policies to work with custom JWT tokens
-- generated by verify-otp function instead of Supabase Auth

-- Drop existing public policies
drop policy if exists "Public profiles access" on profiles;
drop policy if exists "Public books access" on books;
drop policy if exists "Public requests access" on requests;

-- Helper function to get user ID from JWT claims
-- In custom JWT, user ID is stored in 'sub' claim
create or replace function get_user_id()
returns text as $$
begin
  return coalesce(
    nullif(current_setting('request.jwt.claims', true)::json->>'sub', ''),
    nullif(current_setting('request.jwt.claims', true)::json->>'user_id', '')
  );
end;
$$ language plpgsql stable;

-- Profiles: Users can read all public profiles, but only update their own
create policy "Users can read public profiles" on profiles
  for select
  using (is_public = true or get_user_id() = id);

create policy "Users can update own profile" on profiles
  for update
  using (get_user_id() = id)
  with check (get_user_id() = id);

create policy "Users can insert own profile" on profiles
  for insert
  with check (get_user_id() = id);

-- Books: Users can read all books, but only modify their own
create policy "Users can read all books" on books
  for select
  using (true);

create policy "Users can manage own books" on books
  for all
  using (get_user_id() = owner_id)
  with check (get_user_id() = owner_id);

-- Requests: Users can read requests where they are lender or borrower
create policy "Users can read own requests" on requests
  for select
  using (
    get_user_id() = lender_id or 
    get_user_id() = borrower_id
  );

create policy "Users can create requests as borrower" on requests
  for insert
  with check (get_user_id() = borrower_id);

create policy "Lenders can update their requests" on requests
  for update
  using (get_user_id() = lender_id)
  with check (get_user_id() = lender_id);

create policy "Borrowers can update their requests" on requests
  for update
  using (get_user_id() = borrower_id)
  with check (get_user_id() = borrower_id);

-- Note: For demo mode or public access, you can temporarily disable RLS:
-- alter table profiles disable row level security;
-- alter table books disable row level security;
-- alter table requests disable row level security;
